[alias]
example-async-gpt2-api = ["run", "--manifest-path", "examples/async-gpt2-api/Cargo.toml", "--example", "async-gpt2-api", "--target-dir", "target"]
example-cudarc = ["run", "--manifest-path", "examples/cudarc/Cargo.toml", "--example", "cudarc", "--target-dir", "target"]
example-custom-ops = ["run", "--manifest-path", "examples/custom-ops/Cargo.toml", "--example", "custom-ops", "--target-dir", "target"]
example-gpt2 = ["run", "--manifest-path", "examples/gpt2/Cargo.toml", "--example", "gpt2", "--target-dir", "target"]
example-model-info = ["run", "--manifest-path", "examples/model-info/Cargo.toml", "--example", "model-info", "--target-dir", "target"]
example-modnet = ["run", "--manifest-path", "examples/modnet/Cargo.toml", "--example", "modnet", "--target-dir", "target"]
example-phi-3-vision = ["run", "--manifest-path", "examples/phi-3-vision/Cargo.toml", "--target-dir", "target"]
example-semantic-similarity = ["run", "--manifest-path", "examples/sentence-transformers/Cargo.toml", "--example", "semantic-similarity", "--target-dir", "target"]
example-train-pretokenize = ["run", "--manifest-path", "examples/training/Cargo.toml", "--bin", "pretokenize", "--target-dir", "target"]
example-train-clm = ["run", "--manifest-path", "examples/training/Cargo.toml", "--example", "train-clm", "--target-dir", "target"]
example-train-clm-simple = ["run", "--manifest-path", "examples/training/Cargo.toml", "--example", "train-clm-simple", "--target-dir", "target"]
example-yolov8 = ["run", "--manifest-path", "examples/yolov8/Cargo.toml", "--example", "yolov8", "--target-dir", "target"]
leak-check = ["valgrind", "run", "--manifest-path", "tests/leak-check/Cargo.toml", "--target-dir", "target"]
