name: 📋 Code Quality
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/code-quality.yml'
      - 'src/**/*.rs'
      - 'build.rs'
      - 'Cargo.toml'
      - '.cargo/**/*'
      - 'tests/**/*'
      - 'codecov.yml'
      - 'ort-sys/build.rs'
      - 'ort-sys/src/**/*.rs'
      - 'ort-sys/wrapper.h'
      - 'ort-sys/Cargo.toml'
  pull_request:
    paths:
      - '.github/workflows/code-quality.yml'
      - 'src/**/*.rs'
      - 'Cargo.toml'
      - '.cargo/**/*'
      - 'tests/**/*'
      - 'codecov.yml'
      - 'ort-sys/build.rs'
      - 'ort-sys/src/**/*.rs'
      - 'ort-sys/wrapper.h'
      - 'ort-sys/Cargo.toml'
env:
  RUST_BACKTRACE: 1
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_DEV_DEBUG: 0
jobs:
  lint-and-fmt:
    name: Lint & format
    runs-on: ubuntu-24.04
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly-2024-10-18
          components: rustfmt, clippy
      - name: Check fmt
        run: cargo fmt --all -- --check
      - name: Run clippy
        run: cargo clippy -p ort --all-targets --features fetch-models
  coverage:
    name: Code coverage
    runs-on: ubuntu-24.04
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly-2024-10-18
      - name: Get Rust version
        id: rust-version
        run: echo "::set-output name=version::$(cargo --version | cut -d ' ' -f 2)"
        shell: bash
      - uses: actions/cache@v2
        id: tarpaulin-cache
        with:
          path: ~/.cargo/bin/cargo-tarpaulin
          key: ${{ runner.os }}-cargo-${{ steps.rust-version.outputs.version }}-0.31.1
      - name: Install tarpaulin
        if: steps.tarpaulin-cache.outputs.cache-hit != 'true'
        run: cargo install cargo-tarpaulin --version 0.31.1
      - name: Generate code coverage
        run: |
          cargo tarpaulin -p ort --features fetch-models --verbose --timeout 120 --out xml --engine llvm --doc --lib --tests -- --test-threads 1
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
