name: 🚩 Misc Checks
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/other-checks.yml'
      - 'src/**/*.rs'
      - 'examples/**/*'
      - 'ort-sys/**/*.rs'
      - 'ort-sys/**/dist.txt'
      - 'build.rs'
      - 'Cargo.toml'
      - '.cargo/**/*'
      - 'tests/**/*'
  pull_request:
    paths:
      - '.github/workflows/other-checks.yml'
      - 'src/**/*.rs'
      - 'examples/**/*'
      - 'ort-sys/**/*.rs'
      - 'ort-sys/**/dist.txt'
      - 'build.rs'
      - 'Cargo.toml'
      - '.cargo/**/*'
      - 'tests/**/*'
env:
  RUST_BACKTRACE: 1
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_DEV_DEBUG: 0
jobs:
  no-default-features:
    name: --no-default-features
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install stable Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      - name: Run checks
        run: |
          cargo check -p ort --no-default-features
  msrv:
    name: MSRV (1.80)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install stable Rust toolchain
        uses: dtolnay/rust-toolchain@1.80
      - uses: Swatinem/rust-cache@v1
      - name: Run checks
        run: |
          cargo check -p ort
          cargo check -p ort --features load-dynamic
